# Generated by Django 5.1.1 on 2024-11-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecontent',
            name='uuid',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='notetimestamp',
            name='uuid',
            field=models.TextField(unique=True),
        ),
    ]
