# Generated by Django 5.1.1 on 2024-11-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_notelist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notelist',
            name='type',
            field=models.CharField(choices=[('timestamp', 'timestamp'), ('note', 'note')], max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='notelist',
            unique_together={('note', 'index')},
        ),
    ]
