# Generated by Django 5.1.1 on 2024-11-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_notecontent_uuid_alter_notetimestamp_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notecontent',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='notetimestamp',
            name='uuid',
        ),
    ]
