# Generated by Django 5.1.1 on 2024-10-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_note_notecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
