# Generated by Django 5.1.1 on 2024-11-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_notelist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notelist',
            name='type',
            field=models.CharField(choices=[('note', 'note'), ('timestamp', 'timestamp')], max_length=9),
        ),
    ]
