# Generated by Django 5.1.1 on 2024-11-19 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_notecontent_uuid_remove_notetimestamp_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('note', 'note'), ('timestamp', 'timestamp')], max_length=9)),
                ('index', models.IntegerField()),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.notecontent')),
                ('timestamp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.notetimestamp')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('note__isnull', False), ('timestamp', None), ('type', 'note')), models.Q(('note', None), ('timestamp__isnull', False), ('type', 'timestamp')), _connector='OR'), name='one of the two type is not null')],
            },
        ),
    ]
