# Generated by Django 5.1.1 on 2024-11-19 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_notelist_type_alter_notelist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='youtubeurl',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='notelist',
            name='type',
            field=models.CharField(choices=[('note', 'note'), ('timestamp', 'timestamp')], max_length=9),
        ),
        migrations.AlterField(
            model_name='youtubeurl',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtubeURL', to='backend.note', unique=True),
        ),
    ]
