# Generated by Django 5.1.1 on 2024-10-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('user', 'title')},
        ),
    ]
