# Generated by Django 5.1.1 on 2024-11-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_notelist'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notelist',
            name='one of the two type is not null',
        ),
        migrations.AlterField(
            model_name='notelist',
            name='type',
            field=models.CharField(choices=[('timestamp', 'timestamp'), ('note', 'note')], max_length=9),
        ),
        migrations.AddConstraint(
            model_name='notelist',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('note__isnull', False), ('timestamp', None), ('type', 'note')), models.Q(('note', None), ('timestamp__isnull', False), ('type', 'timestamp')), _connector='OR'), name='type and note object does not match'),
        ),
    ]
