# Generated by Django 5.1.1 on 2024-11-19 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_youtubeurl_unique_together_alter_notelist_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notelist',
            name='type',
            field=models.CharField(choices=[('timestamp', 'timestamp'), ('note', 'note')], max_length=9),
        ),
        migrations.AlterField(
            model_name='youtubeurl',
            name='note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youtubeURL', to='backend.note'),
        ),
    ]
