# Generated by Django 5.1.1 on 2024-10-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_note_title_alter_note_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notecontent',
            name='note',
        ),
        migrations.AddField(
            model_name='notecontent',
            name='note',
            field=models.ManyToManyField(related_name='content', to='backend.note'),
        ),
    ]
