# Generated by Django 5.1.1 on 2024-11-29 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_notelist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='backend.note'),
        ),
    ]
