# Generated by Django 5.1.1 on 2024-11-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_notelist_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notecontent',
            old_name='content',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='notelist',
            name='type',
            field=models.CharField(choices=[('note', 'note'), ('timestamp', 'timestamp')], max_length=9),
        ),
    ]
