# Generated by Django 5.1.1 on 2024-11-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_note_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notecontent',
            old_name='subheading',
            new_name='heading',
        ),
        migrations.AlterField(
            model_name='notelist',
            name='type',
            field=models.CharField(choices=[('timestamp', 'timestamp'), ('note', 'note')], max_length=9),
        ),
    ]
