# Generated by Django 5.1.1 on 2024-11-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_rename_subheading_notecontent_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notelist',
            name='type',
            field=models.CharField(choices=[('note', 'note'), ('timestamp', 'timestamp')], max_length=9),
        ),
    ]
