# Generated by Django 5.1.1 on 2024-11-28 01:31

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_notelist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notelist',
            name='type',
            field=models.CharField(choices=[('note', 'note'), ('timestamp', 'timestamp')], max_length=9),
        ),
        migrations.AlterField(
            model_name='youtubeurl',
            name='url',
            field=models.URLField(validators=[backend.models.validate_youtube_url]),
        ),
    ]
