name: Test
on: 
    push:
        branches:
            - main

jobs: 
    test_app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: pipx install -r requirements.txt
            - name: Run Unit test
              run: |
                    cd OnBeat
                    python3 manage.py test
