name: Test
on: 
    push:
        branches:
            - main

jobs: 
    test_app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v1
            - name: Run Unit test
              run: |
                    venv\Scripts\activate
                    pipx install Django
                    cd OnBeat
                    python3 manage.py test
