name: Test
on: 
    push:
        branches:
            - main

jobs: 
    test_app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run Unit test
              run: |
                    pipx install virtualenv
                    python3 -m venv venv
                    source venv/bin/activate
                    python3 -m pip install -r requirements.txt
                    cd OnBeat
                    python3 manage.py test
