name: Test
on: 
    push:
        branches:
            - main

jobs: 
    test_app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run Unit test
              run: |
                    cd OnBeat
                    pipx install virtualenv
                    python3 -m venv venv
                    source venv/bin/activate
                    python -c "import sys; print('\n'.join(sys.path))"
                    python3 -m pip install -U Django
                    python3 -m pip install python-dotenv
                    python3 manage.py test
